### ISSUE TITLE
Everything works fine

### ISSUE THREAD

**Issue by KentEkl** [vlebourl/netatmo_custom#7]
I have been running the beta for my weather station for 24h now without any errors, used to be several error messages.

arch | x86_64
chassis | vm
dev | false
docker | true
docker_version | 19.03.8
hassio | true
host_os | HassOS 4.11
installation_type | Home Assistant OS
os_name | Linux
os_version | 5.4.50
python_version | 3.7.7
supervisor | 228
timezone | Europe/Stockholm
version | 0.112.4
virtualenv | false

**Comment by cgtobi** [comment]
Thanks for the feedback. This is very appreciated.
